version: '2.3'

volumes:
  workspace:

services:

  #xserver:
  #  image: wn1980/xserver${TAG}
  #  container_name: turtlebot2_xserver
  #  init: true
  #  restart: unless-stopped
  #  volumes:
  #  - "/etc/localtime:/etc/localtime:ro"
  #  ports:
  #  - "6905:6901"
  #  healthcheck:
  #    test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
  #    interval: "1m"
  #    retries: 20

  turtlebot2:
    build: .
    image: wn1980/turtlebot2-melodic${TAG}
    container_name: turtlebot2_melodic
    init: true
    restart: unless-stopped
    #volumes_from:
    #  - xserver
    #depends_on:
    #  - xserver
    environment:
      - DISPLAY=:1
      #- QT_X11_NO_MITSHM=1
      #- ROS_MASTER_URI=http://localhost:11311
      #- TURTLEBOT_3D_SENSOR=asus_xtion_pro
    privileged: true
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/run/systemd:/run/systemd"
      - "/etc/localtime:/etc/localtime:ro"
      - workspace:/root/workspace
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
      interval: "1m"
      retries: 20
    ports:
      #- "11311:11311"
      - "8558:8558"
      - "9901:9901"
