version: '2.3'

networks:
  default:
    external:
      name: ros-network

volumes:
  workspace:

services:

  master:
    image: ros:melodic-ros-core-bionic
    container_name: ros1_master
    init: true
    restart: always
    command: roscore
    expose:
      - 11311
    ports:
      - "11311:11311"

  turtlebot2:
    #build: ./image
    image: wn1980/turtlebot2-melodic${TAG}
    container_name: ros_turtlebot2_melodic
    init: true
    restart: unless-stopped
    #volumes_from:
    #  - xserver
    #depends_on:
    #  - xserver
    environment:
      - DISPLAY=:1
      #- QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://master:11311
      #- TURTLEBOT_3D_SENSOR=asus_xtion_pro
    privileged: true
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/run/systemd:/run/systemd"
      - "/etc/localtime:/etc/localtime:ro"
      - "~/.gitconfig:/home/developer/.gitconfig"
      - workspace:/workspace
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
      interval: "1m"
      retries: 20
    ports:
      #- "11311:11311"
      - "8558:8008"
      - "3901:6901"
